language: java

os:
  - osx

matrix:
  include:
  - os: linux
    jdk: openjdk6
  - os: linux
    jdk: openjdk7
  - os: linux
    jdk: oraclejdk7
  - os: linux
    jdk: oraclejdk8

script: mvn clean test
