language: java

matrix:
  include:
  - os: linux
    jdk: openjdk6
  - os: linux
    jdk: openjdk7
  - os: linux
    jdk: oraclejdk7
  - os: linux
    jdk: oraclejdk8
  - os: osx
    osx_image: xcode6.4
  - os: osx
    osx_image: xcode7.3
  - os: osx
    osx_image: xcode8.2

script: mvn clean test
