language: java

os:
  - osx

osx_image:
  - xcode6.4
  - xcode7.3
  - xcode8.2

matrix:
  include:
  - os: linux
    jdk: openjdk6
  - os: linux
    jdk: openjdk7
  - os: linux
    jdk: oraclejdk7
  - os: linux
    jdk: oraclejdk8

script: mvn clean test
