language: java

os:
  - linux
  - osx

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8

matrix:
  exclude:
  - os: osx
    jdk: openjdk6
  - os: osx
    jdk: openjdk7
  - os: osx
    jdk: oraclejdk7
  - os: osx
    jdk: oraclejdk8


script: mvn clean test
